# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.URLField(default=None, max_length=128),
        ),
    ]
